taxonomy: SARS2
gene: SARS2RdRP
fragmentOptions:
- name: Fingers
  seqFragment: [336, 581]
- name: Palm
  seqFragment: [680, 815]
- name: Thumb
  seqFragment: [816, 932]
- name: All
  seqFragment: [1, 932]
annotCategories:
- name: subdomain
  dropdown: false
  defaultAnnot: subdomain
  multiSelect: false
  annotStyle: colorBox
  annotNames: [subdomain]
- name: polymorphism
  dropdown: true
  defaultAnnot: var2000
  multiSelect: false
  annotStyle: aminoAcids
  color: '#000'
  annotNames: [var2000]
- name: _hide
  display: false
  dropdown: false
  defaultAnnot: null
  multiSelect: false
  annotStyle: hide
  annotNames: [_hide2]
- name: _hide2
  display: false
  dropdown: false
  defaultAnnot: _hide2
  multiSelect: false
  annotStyle: underscore
  annotNames: [_hide2]
