taxonomy: SARS2
gene: SARS2RdRP
refSequence: SADAQSFLNRVCGVSAARLTPCGTGTSTDVVYRAFDIYNDKVAGFAKFLKTNCCRFQEKDEDDNLIDSYFVVKRHTFSNYQHEETIYNLLKDCPAVAKHDFFKFRIDGDMVPHISRQRLTKYTMADLVYALRHFDEGNCDTLKEILVTYNCCDDDYFNKKDWYDFVENPDILRVYANLGERVRQALLKTVQFCDAMRNAGIVGVLTLDNQDLNGNWYDFGDFIQTTPGSGVPVVDSYYSLLMPILTLTRALTAESHVDTDLTKPYIKWDLLKYDFTEERLKLFDRYFKYWDQTYHPNCVNCLDDRCILHCANFNVLFSTVFPPTSFGPLVRKIFVDGVPFVVSTGYHFRELGVVHNQDVNLHSSRLSFKELLVYAADPAMHAASGNLLLDKRTTCFSVAALTNNVAFQTVKPGNFNKDFYDFAVSKGFFKEGSSVELKHFFFAQDGNAAISDYDYYRYNLPTMCDIRQLLFVVEVVDKYFDCYDGGCINANQVIVNNLDKSAGFPFNKWGKARLYYDSMSYEDQDALFAYTKRNVIPTITQMNLKYAISAKNRARTVAGVSICSTMTNRQFHQKLLKSIAATRGATVVIGTSKFYGGWHNMLKTVYSDVENPHLMGWDYPKCDRAMPNMLRIMASLVLARKHTTCCSLSHRFYRLANECAQVLSEMVMCGGSLYVKPGGTSSGDATTAYANSVFNICQAVTANVNALLSTDGNKIADKYVRNLQHRLYECLYRNRDVDTDFVNEFYAYLRKHFSMMILSDDAVVCFNSTYASQGLVASIKNFKSVLYYQNNVFMSEAKCWTETDLTKGPHEFCSQHTMLVKQGDDYVYLPYPDPSRILGAGCFVDDIVKTDGTLMIERFVSLAIDAYPLTKHPNQEYADVFHLYLQYIRKLHDELTGHMLDMYSVMLTNDNTSRYWEPEFYEAMYTPHTVLQ
fragmentOptions:
- name: Fingers & Palm
  seqFragment: [356, 825]
- name: All
  seqFragment: [1, 932]
annotCategories:
- name: subdomain
  dropdown: false
  defaultAnnot: subdomain
  multiSelect: false
  annotStyle: colorBox
  annotNames: [subdomain]
- name: polymorphism
  dropdown: true
  defaultAnnot: var2000
  multiSelect: false
  annotStyle: aminoAcids
  color: '#999'
  annotNames: [var2000]
- name: cov-diff
  display: diff from other Human-CoV
  dropdown: true
  defaultAnnot: sars
  multiSelect: false
  annotStyle: aminoAcids
  annotNames: [sars, mers, oc43, hku1, nl63, 229e]
- name: _hide
  display: false
  dropdown: false
  defaultAnnot: null
  multiSelect: false
  annotStyle: hide
  annotNames: [_hide2]
- name: motif
  display: motifs
  dropdown: true
  defaultAnnots:
  - Motif A
  - Motif B
  - Motif C
  - Motif D
  - Motif E
  - Motif F
  - Motif G
  multiSelect: true
  annotStyle: underscore
  annotNames:
  - Motif A
  - Motif B
  - Motif C
  - Motif D
  - Motif E
  - Motif F
  - Motif G
