taxonomy: SARS2
gene: RdRP
refSequence: SADAQSFLNRVCGVSAARLTPCGTGTSTDVVYRAFDIYNDKVAGFAKFLKTNCCRFQEKDEDDNLIDSYFVVKRHTFSNYQHEETIYNLLKDCPAVAKHDFFKFRIDGDMVPHISRQRLTKYTMADLVYALRHFDEGNCDTLKEILVTYNCCDDDYFNKKDWYDFVENPDILRVYANLGERVRQALLKTVQFCDAMRNAGIVGVLTLDNQDLNGNWYDFGDFIQTTPGSGVPVVDSYYSLLMPILTLTRALTAESHVDTDLTKPYIKWDLLKYDFTEERLKLFDRYFKYWDQTYHPNCVNCLDDRCILHCANFNVLFSTVFPPTSFGPLVRKIFVDGVPFVVSTGYHFRELGVVHNQDVNLHSSRLSFKELLVYAADPAMHAASGNLLLDKRTTCFSVAALTNNVAFQTVKPGNFNKDFYDFAVSKGFFKEGSSVELKHFFFAQDGNAAISDYDYYRYNLPTMCDIRQLLFVVEVVDKYFDCYDGGCINANQVIVNNLDKSAGFPFNKWGKARLYYDSMSYEDQDALFAYTKRNVIPTITQMNLKYAISAKNRARTVAGVSICSTMTNRQFHQKLLKSIAATRGATVVIGTSKFYGGWHNMLKTVYSDVENPHLMGWDYPKCDRAMPNMLRIMASLVLARKHTTCCSLSHRFYRLANECAQVLSEMVMCGGSLYVKPGGTSSGDATTAYANSVFNICQAVTANVNALLSTDGNKIADKYVRNLQHRLYECLYRNRDVDTDFVNEFYAYLRKHFSMMILSDDAVVCFNSTYASQGLVASIKNFKSVLYYQNNVFMSEAKCWTETDLTKGPHEFCSQHTMLVKQGDDYVYLPYPDPSRILGAGCFVDDIVKTDGTLMIERFVSLAIDAYPLTKHPNQEYADVFHLYLQYIRKLHDELTGHMLDMYSVMLTNDNTSRYWEPEFYEAMYTPHTVLQ
fragmentOptions:
- name: All
  seqFragment: [1, 932]
- name: Fingers & Palm
  seqFragment: [356, 825]
annotCategories:
- name: subdomain
  dropdown: false
  defaultAnnot: subdomain
  multiSelect: false
  annotStyle: colorBox
  annotNames: [subdomain]
- name: motif
  display: motifs
  dropdown: true
  defaultAnnots:
  - Motif A
  - Motif B
  - Motif C
  - Motif D
  - Motif E
  - Motif F
  - Motif G
  multiSelect: true
  annotStyle: underscore
  annotNames:
  - Motif A
  - Motif B
  - Motif C
  - Motif D
  - Motif E
  - Motif F
  - Motif G
- name: variants
  display: variants
  dropdown: true
  multiSelect: false
  annotStyle: aminoAcids
  color: '#483d8b'
  variantQuery:
  - "Omicron/BQ.1.1"
  - "Omicron/BQ.1"
  - "Omicron/BA.5"
  - "Omicron/BF.7"
  - "Omicron/BA.4.6"
  - "Omicron/XBB"
  - "Omicron/BN.1"
  - "Omicron/BA.2.75"
  - "Omicron/BA.4"
  - "Omicron/BA.2"
  - "Omicron/BA.1"
  - "Alpha"
  - "Beta"
  - "Gamma"
  - "Delta"
  - "Epsilon"
  - "Zeta"
  - "Eta"
  - "Theta"
  - "Iota"
  - "Kappa"
  - "Lambda"
  - "Mu"
- name: cov-diff
  display: diff from other CoV
  dropdown: true
  multiSelect: false
  annotStyle: aminoAcids
  color: '#1e8d9e'
  annotNames: [sars, mers, oc43, hku1, nl63, 229e, mhv]
- name: drms
  display: resistance mutations
  defaultAnnot: drms
  dropdown: false
  checkbox: true
  annotStyle: aminoAcids
  color: '#cc3429'
  drmQuery: |-
    SELECT position, amino_acid FROM resistance_mutations drm
    WHERE
      gene = 'RdRP'
    ORDER BY position, amino_acid
