taxonomy: SARS2
gene: SARS2RdRP
refSequence: MFVFLVLLPLVSSQCVNLTTRTQLPPAYTNSFTRGVYYPDKVFRSSVLHSTQDLFLPFFSNVTWFHAIHVSGTNGTKRFDNPVLPFNDGVYFASTEKSNIIRGWIFGTTLDSKTQSLLIVNNATNVVIKVCEFQFCNDPFLGVYYHKNNKSWMESEFRVYSSANNCTFEYVSQPFLMDLEGKQGNFKNLREFVFKNIDGYFKIYSKHTPINLVRDLPQGFSALEPLVDLPIGINITRFQTLLALHRSYLTPGDSSSGWTAGAAAYYVGYLQPRTFLLKYNENGTITDAVDCALDPLSETKCTLKSFTVEKGIYQTSNFRVQPTESIVRFPNITNLCPFGEVFNATRFASVYAWNRKRISNCVADYSVLYNSASFSTFKCYGVSPTKLNDLCFTNVYADSFVIRGDEVRQIAPGQTGKIADYNYKLPDDFTGCVIAWNSNNLDSKVGGNYNYLYRLFRKSNLKPFERDISTEIYQAGSTPCNGVEGFNCYFPLQSYGFQPTNGVGYQPYRVVVLSFELLHAPATVCGPKKSTNLVKNKCVNFNFNGLTGTGVLTESNKKFLPFQQFGRDIADTTDAVRDPQTLEILDITPCSFGGVSVITPGTNTSNQVAVLYQDVNCTEVPVAIHADQLTPTWRVYSTGSNVFQTRAGCLIGAEHVNNSYECDIPIGAGICASYQTQTNSPRRARSVASQSIIAYTMSLGAENSVAYSNNSIAIPTNFTISVTTEILPVSMTKTSVDCTMYICGDSTECSNLLLQYGSFCTQLNRALTGIAVEQDKNTQEVFAQVKQIYKTPPIKDFGGFNFSQILPDPSKPSKRSFIEDLLFNKVTLADAGFIKQYGDCLGDIAARDLICAQKFNGLTVLPPLLTDEMIAQYTSALLAGTITSGWTFGAGAALQIPFAMQMAYRFNGIGVTQNVLYENQKLIANQFNSAIGKIQDSLSSTASALGKLQDVVNQNAQALNTLVKQLSSNFGAISSVLNDILSRLDKVEAEVQIDRLITGRLQSLQTYVTQQLIRAAEIRASANLAATKMSECVLGQSKRVDFCGKGYHLMSFPQSAPHGVVFLHVTYVPAQEKNFTTAPAICHDGKAHFPREGVFVSNGTHWFVTQRNFYEPQIITTDNTFVSGNCDVVIGIVNNTVYDPLQPELDSFKEELDKYFKNHTSPDVDLGDISGINASVVNIQKEIDRLNEVAKNLNESLIDLQELGKYEQYIKWPWYIWLGFIAGLIAIVMVTIMLCCMTSCCSCLKGCCSCGSCCKFDEDDSEPVLKGVKLHYT
fragmentOptions:
- name: S1
  seqFragment: [1, 686]
- name: RBD
  seqFragment: [306, 534]
- name: S2
  seqFragment: [681, 1273]
- name: All
  seqFragment: [1, 1273]
annotCategories:
- name: subdomain
  dropdown: false
  defaultAnnot: subdomain
  multiSelect: false
  annotStyle: colorBox
  annotNames: [subdomain]
- name: ace2
  dropdown: false
  defaultAnnot: ACE2
  multiSelect: false
  annotStyle: circleInBox
  annotNames: [ACE2]
- name: antibody
  display: antibodies
  dropdown: true
  defaultAnnots: []
  multiSelect: true
  annotStyle: underscore
  annotNames:
  - CR3022
  - EY6A
  - S309
  - P2B-2F6
  - BD23
  - 2-4
  - H11-D4
  - H11-H4
  - B38
  - CB6
  - C105
  - CC12.1
  - CC12.3
  - CV30
  - REGN10987
  - REGN10933
- name: polymorphism
  dropdown: true
  defaultAnnot: var2000
  multiSelect: false
  annotStyle: aminoAcids
  color: '#999'
  annotNames:
  - var2000
  - var1000
- name: escapeMutants
  display: escape mutants
  dropdown: true
  defaultAnnot: escape mutants
  multiSelect: false
  annotStyle: aminoAcids
  annotNames:
  - escape mutants
  - escape mutants Baum20
  - escape mutants Weisblum20
- name: _hide
  display: false
  dropdown: false
  defaultAnnot:
  multiSelect: false
  annotStyle: hide
  annotNames:
  - secondary structure
  - Glycan
  - Cysteine residue
conditionalComments:
- commentName: subdomain
  rank: 1  # highest: 1
  condition:
    func: hasAnnot
    args: [subdomain]
  prefix:
    func: position
  template: >-
    located in subdomain $SUBDOMAIN
  values:
    SUBDOMAIN:
      func: getSubgroup
      args: [subdomain]
- commentName: ace2
  rank: 2
  condition:
    func: hasAnnot
    args: [ACE2]
  prefix:
    func: position
  template: >-
    involved in ACE2 binding
- commentName: antibody
  rank: 3
  condition:
    func: hasAnnotCategory
    args: [antibody]
  prefix:
    func: position
  template: >-
    an epitope binding to $ANTIBODIES
  values:
    ANTIBODIES:
      func: joinAnnotCatSubgroup
      args: [antibody]
- commentName: escapeMutants
  rank: 4
  condition:
    func: hasAnnot
    args: [escape mutants]
  prefix:
    func: mutation
    args: [escape mutants]
  templateSingular: >-
    a mutation that escape antibody neutralization
  templatePlural: >-
    mutations that escape antibody neutralization
- commentName: polymorphism
  rank: 5
  condition:
    func: hasAnnot
    args: [var2000]
  prefix:
    func: mutation
    args: [var2000]
  templateSingular: >-
    a polymorphic mutation
  templatePlural: >-
    polymorphic mutations
