taxonomy: SARS2
gene: SARS2RdRP
refSequence: MFVFLVLLPLVSSQCVNLTTRTQLPPAYTNSFTRGVYYPDKVFRSSVLHSTQDLFLPFFSNVTWFHAIHVSGTNGTKRFDNPVLPFNDGVYFASTEKSNIIRGWIFGTTLDSKTQSLLIVNNATNVVIKVCEFQFCNDPFLGVYYHKNNKSWMESEFRVYSSANNCTFEYVSQPFLMDLEGKQGNFKNLREFVFKNIDGYFKIYSKHTPINLVRDLPQGFSALEPLVDLPIGINITRFQTLLALHRSYLTPGDSSSGWTAGAAAYYVGYLQPRTFLLKYNENGTITDAVDCALDPLSETKCTLKSFTVEKGIYQTSNFRVQPTESIVRFPNITNLCPFGEVFNATRFASVYAWNRKRISNCVADYSVLYNSASFSTFKCYGVSPTKLNDLCFTNVYADSFVIRGDEVRQIAPGQTGKIADYNYKLPDDFTGCVIAWNSNNLDSKVGGNYNYLYRLFRKSNLKPFERDISTEIYQAGSTPCNGVEGFNCYFPLQSYGFQPTNGVGYQPYRVVVLSFELLHAPATVCGPKKSTNLVKNKCVNFNFNGLTGTGVLTESNKKFLPFQQFGRDIADTTDAVRDPQTLEILDITPCSFGGVSVITPGTNTSNQVAVLYQDVNCTEVPVAIHADQLTPTWRVYSTGSNVFQTRAGCLIGAEHVNNSYECDIPIGAGICASYQTQTNSPRRARSVASQSIIAYTMSLGAENSVAYSNNSIAIPTNFTISVTTEILPVSMTKTSVDCTMYICGDSTECSNLLLQYGSFCTQLNRALTGIAVEQDKNTQEVFAQVKQIYKTPPIKDFGGFNFSQILPDPSKPSKRSFIEDLLFNKVTLADAGFIKQYGDCLGDIAARDLICAQKFNGLTVLPPLLTDEMIAQYTSALLAGTITSGWTFGAGAALQIPFAMQMAYRFNGIGVTQNVLYENQKLIANQFNSAIGKIQDSLSSTASALGKLQDVVNQNAQALNTLVKQLSSNFGAISSVLNDILSRLDKVEAEVQIDRLITGRLQSLQTYVTQQLIRAAEIRASANLAATKMSECVLGQSKRVDFCGKGYHLMSFPQSAPHGVVFLHVTYVPAQEKNFTTAPAICHDGKAHFPREGVFVSNGTHWFVTQRNFYEPQIITTDNTFVSGNCDVVIGIVNNTVYDPLQPELDSFKEELDKYFKNHTSPDVDLGDISGINASVVNIQKEIDRLNEVAKNLNESLIDLQELGKYEQYIKWPWYIWLGFIAGLIAIVMVTIMLCCMTSCCSCLKGCCSCGSCCKFDEDDSEPVLKGVKLHYT
fragmentOptions:
- name: S1
  seqFragment: [1, 686]
- name: RBD
  seqFragment: [306, 534]
- name: S2
  seqFragment: [681, 1273]
- name: All
  seqFragment: [1, 1273]
annotCategories:
- name: subdomain
  dropdown: false
  defaultAnnot: subdomain
  multiSelect: false
  annotStyle: colorBox
  annotNames: [subdomain]
- name: ace2
  dropdown: false
  defaultAnnot: ACE2
  multiSelect: false
  annotStyle: circleInBox
  annotNames: [ACE2]
- name: antibody
  display: antibodies
  dropdown: true
  defaultAnnots: []
  multiSelect: true
  annotStyle: underscore
  annotNames:
  - CR3022
  - EY6A
  - S309
  - P2B-2F6
  - BD23
  - 2-4
  - H11-D4
  - H11-H4
  - B38
  - CB6
  - C105
  - CC12.1
  - CC12.3
  - CV30
  - REGN10987
  - REGN10933
- name: polymorphism
  dropdown: true
  defaultAnnot: var2000
  multiSelect: false
  annotStyle: aminoAcids
  color: '#000'
  annotNames:
  - var2000
  - var1000
- name: escapeMutants
  display: escape mutants
  dropdown: true
  defaultAnnot: escape mutants
  multiSelect: false
  annotStyle: aminoAcids
  annotNames:
  - escape mutants
  - escape mutants Baum20
  - escape mutants Weisblum20
- name: _hide
  display: false
  dropdown: false
  defaultAnnot:
  multiSelect: false
  annotStyle: hide
  annotNames:
  - secondary structure
  - Glycan
  - Cysteine residue
