taxonomy: SARS2
gene: SARS2RdRP
refSequence: MFVFLVLLPLVSSQCVNLTTRTQLPPAYTNSFTRGVYYPDKVFRSSVLHSTQDLFLPFFSNVTWFHAIHVSGTNGTKRFDNPVLPFNDGVYFASTEKSNIIRGWIFGTTLDSKTQSLLIVNNATNVVIKVCEFQFCNDPFLGVYYHKNNKSWMESEFRVYSSANNCTFEYVSQPFLMDLEGKQGNFKNLREFVFKNIDGYFKIYSKHTPINLVRDLPQGFSALEPLVDLPIGINITRFQTLLALHRSYLTPGDSSSGWTAGAAAYYVGYLQPRTFLLKYNENGTITDAVDCALDPLSETKCTLKSFTVEKGIYQTSNFRVQPTESIVRFPNITNLCPFGEVFNATRFASVYAWNRKRISNCVADYSVLYNSASFSTFKCYGVSPTKLNDLCFTNVYADSFVIRGDEVRQIAPGQTGKIADYNYKLPDDFTGCVIAWNSNNLDSKVGGNYNYLYRLFRKSNLKPFERDISTEIYQAGSTPCNGVEGFNCYFPLQSYGFQPTNGVGYQPYRVVVLSFELLHAPATVCGPKKSTNLVKNKCVNFNFNGLTGTGVLTESNKKFLPFQQFGRDIADTTDAVRDPQTLEILDITPCSFGGVSVITPGTNTSNQVAVLYQDVNCTEVPVAIHADQLTPTWRVYSTGSNVFQTRAGCLIGAEHVNNSYECDIPIGAGICASYQTQTNSPRRARSVASQSIIAYTMSLGAENSVAYSNNSIAIPTNFTISVTTEILPVSMTKTSVDCTMYICGDSTECSNLLLQYGSFCTQLNRALTGIAVEQDKNTQEVFAQVKQIYKTPPIKDFGGFNFSQILPDPSKPSKRSFIEDLLFNKVTLADAGFIKQYGDCLGDIAARDLICAQKFNGLTVLPPLLTDEMIAQYTSALLAGTITSGWTFGAGAALQIPFAMQMAYRFNGIGVTQNVLYENQKLIANQFNSAIGKIQDSLSSTASALGKLQDVVNQNAQALNTLVKQLSSNFGAISSVLNDILSRLDKVEAEVQIDRLITGRLQSLQTYVTQQLIRAAEIRASANLAATKMSECVLGQSKRVDFCGKGYHLMSFPQSAPHGVVFLHVTYVPAQEKNFTTAPAICHDGKAHFPREGVFVSNGTHWFVTQRNFYEPQIITTDNTFVSGNCDVVIGIVNNTVYDPLQPELDSFKEELDKYFKNHTSPDVDLGDISGINASVVNIQKEIDRLNEVAKNLNESLIDLQELGKYEQYIKWPWYIWLGFIAGLIAIVMVTIMLCCMTSCCSCLKGCCSCGSCCKFDEDDSEPVLKGVKLHYT
fragmentOptions:
- name: S1
  seqFragment: [1, 686]
- name: RBD
  seqFragment: [306, 534]
- name: S2
  seqFragment: [681, 1273]
- name: All
  seqFragment: [1, 1273]
annotCategories:
- name: subdomain
  dropdown: false
  defaultAnnot: subdomain
  multiSelect: false
  annotStyle: colorBox
  annotNames: [subdomain]
- name: ace2
  dropdown: false
  defaultAnnot: ACE2
  multiSelect: false
  annotStyle: circleInBox
  annotNames: [ACE2]
- name: antibody
  display: antibodies
  dropdown: true
  defaultAnnots: []
  multiSelect: true
  annotStyle: underscore
  annotNames:
  - CR3022
  - EY6A
  - S309
  - P2B-2F6
  - BD-23
  - BD-236
  - BD-368-2
  - BD-604
  - BD-629
  - C002
  - C105
  - C121
  - C135
  - C144
  - 2-4
  - COVA1-16
  - COVA2-04
  - COVA2-39
  - H11-D4
  - H11-H4
  - B38
  - CB6
  - CC12.1
  - CC12.3
  - CV30
  - CV07-250
  - CV07-270
  - REGN10987
  - REGN10933
  - 4A8
  - H014
  - MR17-K99Y
  - Sb23
  - SR4
  - Ty1
- name: polymorphism
  dropdown: true
  defaultAnnot: var2000
  multiSelect: false
  annotStyle: aminoAcids
  color: '#999'
  annotNames:
  - var2000
  - var1000
- name: escapeMutants
  display: escape mutants
  dropdown: true
  defaultAnnot: escape mutants
  multiSelect: false
  annotStyle: aminoAcids
  annotNames:
  - escape mutants
  - escape mutants Baum20
  - escape mutants Weisblum20
- name: _hide
  display: false
  dropdown: false
  defaultAnnot:
  multiSelect: false
  annotStyle: hide
  annotNames:
  - secondary structure
  - glycan
  - cysteine
  - cleavage
  - subdomain RBM
  - neutralizing sera resistance
conditionalComments:
- commentName: subdomain
  rank: 1  # highest: 1
  condition:
    func: hasAnnotExceptSubgroups
    args: [subdomain, S1/S2, "S2'"]
  prefix:
    func: position
  template: >-
    located in subdomain $SUBDOMAIN
  variables:
    SUBDOMAIN:
      func: getSubgroup
      args: [subdomain]
  triggeredAAs: "*"
- commentName: cleavage
  rank: 2  # highest: 1
  condition:
    func: hasAnnot
    args: [cleavage]
  prefix:
    func: position
  template: >-
    located in cleavage site $CLEAVAGE
  variables:
    CLEAVAGE:
      func: getSubgroup
      args: [cleavage]
  triggeredAAs: "*"
- commentName: ace2
  rank: 3
  condition:
    func: hasAnnot
    args: [ACE2]
  prefix:
    func: position
  template: >-
    involved in ACE2 binding
  footnote: ${FN}
  variables:
    FN:
      func: getCitations
      args: [ACE2]
  triggeredAAs: "*"
- commentName: glycan
  rank: 4
  condition:
    func: hasAnnot
    args: [glycan]
  prefix:
    func: position
  template: >-
    the position of a N-linked glycosylation sequon
  triggeredAAs: "*"
- commentName: antibody
  rank: 5
  condition:
    func: hasAnnotCategory
    args: [antibody]
  prefix:
    func: position
  template: >-
    an epitope binding to $ANTIBODIES
  variables:
    ANTIBODIES:
      func: joinAnnotCatSubgroup
      args: [antibody]
      keywords:
        footnote: true
  triggeredAAs: "*"
- commentName: cysteine
  rank: 6
  condition:
    func: hasAnnot
    args: [cysteine]
  prefix:
    func: position
  template: >-
    one of the nine cysteine residues found in RBD
  triggeredAAs: "*"
- commentName: escapeMutantsACE2
  rank: 7
  condition:
    func: all
    args:
    - func: hasAnnot
      args: [escape mutants]
    - func: hasAnnot
      args: [ACE2]
  prefix:
    func: mutation
    args: [escape mutants]
  templateSingular: >-
    a mutation that escape ACE2-competing neutralizing mAbs that bind to RBD
  templatePlural: >-
    mutations that escape ACE2-competing neutralizing mAbs that bind to RBD
  footnote: ${FN}
  variables:
    FN:
      func: getCitations
      args: [escape mutants]
  triggeredAAs:
    func: mutation
    args: [escape mutants]
- commentName: escapeMutantsRBM
  rank: 8
  condition:
    func: all
    args:
    - func: hasAnnot
      args: [escape mutants]
    - func: hasAnnot
      args: [subdomain RBM]
    - func: not
      args:
      - func: hasAnnot
        args: [ACE2]
  prefix:
    func: mutation
    args: [escape mutants]
  templateSingular: >-
    a mutation that escape neutralizing mAbs that bind to RBM
  templatePlural: >-
    mutations that escape neutralizing mAbs that bind to RBM
  footnote: ${FN}
  variables:
    FN:
      func: getCitations
      args: [escape mutants]
  triggeredAAs:
    func: mutation
    args: [escape mutants]
- commentName: escapeMutantsRBD
  rank: 9
  condition:
    func: all
    args:
    - func: hasAnnot
      args: [escape mutants]
    - func: hasAnnot
      args: [subdomain]
      keywords:
        subgroup: RBD
    - func: not
      args:
      - func: hasAnnot
        args: [ACE2]
    - func: not
      args:
      - func: hasAnnot
        args: [subdomain RBM]
  prefix:
    func: mutation
    args: [escape mutants]
  templateSingular: >-
    a mutation that escape neutralizing mAbs that bind to RBD
  templatePlural: >-
    mutations that escape neutralizing mAbs that bind to RBD
  footnote: ${FN}
  variables:
    FN:
      func: getCitations
      args: [escape mutants]
  triggeredAAs:
    func: mutation
    args: [escape mutants]
- commentName: escapeMutantsNTD
  rank: 10
  condition:
    func: all
    args:
    - func: hasAnnot
      args: [escape mutants]
    - func: hasAnnot
      args: [subdomain]
      keywords:
        subgroup: NTD
  prefix:
    func: mutation
    args: [escape mutants]
  templateSingular: >-
    a mutation that escape neutralizing mAbs that bind to NTD
  templatePlural: >-
    mutations that escape neutralizing mAbs that bind to NTD
  footnote: ${FN}
  variables:
    FN:
      func: getCitations
      args: [escape mutants]
  triggeredAAs:
    func: mutation
    args: [escape mutants]
- commentName: neutralizing-sera-resistance
  rank: 11
  condition:
    func: hasAnnot
    args: [neutralizing sera resistance]
  prefix:
    func: mutation
    args: [neutralizing sera resistance]
  templateSingular: >-
    a mutation that result in resistance to aliquotes of neutralizing sera
  templatePlural: >-
    mutations that result in resistance to aliquotes of neutralizing sera
  footnote: ${FN}
  variables:
    FN:
      func: getCitations
      args: [neutralizing sera resistance]
  triggeredAAs:
    func: mutation
    args: [neutralizing sera resistance]
- commentName: polymorphism
  rank: 12
  condition:
    func: hasAnnot
    args: [var2000]
  prefix:
    func: mutation
    args: [var2000]
  templateSingular: >-
    a polymorphic mutation
  templatePlural: >-
    polymorphic mutations
  triggeredAAs:
    func: mutation
    args: [var2000]
