taxonomy: SARS2
gene: S
refSequence: MFVFLVLLPLVSSQCVNLTTRTQLPPAYTNSFTRGVYYPDKVFRSSVLHSTQDLFLPFFSNVTWFHAIHVSGTNGTKRFDNPVLPFNDGVYFASTEKSNIIRGWIFGTTLDSKTQSLLIVNNATNVVIKVCEFQFCNDPFLGVYYHKNNKSWMESEFRVYSSANNCTFEYVSQPFLMDLEGKQGNFKNLREFVFKNIDGYFKIYSKHTPINLVRDLPQGFSALEPLVDLPIGINITRFQTLLALHRSYLTPGDSSSGWTAGAAAYYVGYLQPRTFLLKYNENGTITDAVDCALDPLSETKCTLKSFTVEKGIYQTSNFRVQPTESIVRFPNITNLCPFGEVFNATRFASVYAWNRKRISNCVADYSVLYNSASFSTFKCYGVSPTKLNDLCFTNVYADSFVIRGDEVRQIAPGQTGKIADYNYKLPDDFTGCVIAWNSNNLDSKVGGNYNYLYRLFRKSNLKPFERDISTEIYQAGSTPCNGVEGFNCYFPLQSYGFQPTNGVGYQPYRVVVLSFELLHAPATVCGPKKSTNLVKNKCVNFNFNGLTGTGVLTESNKKFLPFQQFGRDIADTTDAVRDPQTLEILDITPCSFGGVSVITPGTNTSNQVAVLYQDVNCTEVPVAIHADQLTPTWRVYSTGSNVFQTRAGCLIGAEHVNNSYECDIPIGAGICASYQTQTNSPRRARSVASQSIIAYTMSLGAENSVAYSNNSIAIPTNFTISVTTEILPVSMTKTSVDCTMYICGDSTECSNLLLQYGSFCTQLNRALTGIAVEQDKNTQEVFAQVKQIYKTPPIKDFGGFNFSQILPDPSKPSKRSFIEDLLFNKVTLADAGFIKQYGDCLGDIAARDLICAQKFNGLTVLPPLLTDEMIAQYTSALLAGTITSGWTFGAGAALQIPFAMQMAYRFNGIGVTQNVLYENQKLIANQFNSAIGKIQDSLSSTASALGKLQDVVNQNAQALNTLVKQLSSNFGAISSVLNDILSRLDKVEAEVQIDRLITGRLQSLQTYVTQQLIRAAEIRASANLAATKMSECVLGQSKRVDFCGKGYHLMSFPQSAPHGVVFLHVTYVPAQEKNFTTAPAICHDGKAHFPREGVFVSNGTHWFVTQRNFYEPQIITTDNTFVSGNCDVVIGIVNNTVYDPLQPELDSFKEELDKYFKNHTSPDVDLGDISGINASVVNIQKEIDRLNEVAKNLNESLIDLQELGKYEQYIKWPWYIWLGFIAGLIAIVMVTIMLCCMTSCCSCLKGCCSCGSCCKFDEDDSEPVLKGVKLHYT
fragmentOptions:
- name: S1
  seqFragment: [1, 686]
- name: RBD
  seqFragment: [306, 534]
- name: S2
  seqFragment: [681, 1273]
- name: All
  seqFragment: [1, 1273]
annotCategories:
- name: subdomain
  dropdown: false
  defaultAnnot: subdomain
  multiSelect: false
  annotStyle: colorBox
  annotNames: [subdomain]
- name: ace2
  dropdown: false
  defaultAnnot: ACE2
  multiSelect: false
  annotStyle: circleInBox
  annotNames: [ACE2]
- name: epitopes
  display: mAb epitope
  dropdown: true
  defaultAnnots: []
  multiSelect: true
  annotStyle: underscore
  epitopeQuery: |-
    SELECT ab_name FROM antibodies ab
    WHERE
      availability in ('EUA', 'KR-Approved', 'CN-Approved') AND
      EXISTS (
        SELECT 1 FROM antibody_epitopes abe
        WHERE ab.ab_name = abe.ab_name
      )
    ORDER BY priority
- name: variants
  display: variants
  dropdown: true
  multiSelect: false
  annotStyle: aminoAcids
  color: '#483d8b'
  variantQuery:
  - "Omicron/BQ.1.1"
  - "Omicron/BQ.1"
  - "Omicron/BA.5"
  - "Omicron/BF.7"
  - "Omicron/BA.4.6"
  - "Omicron/XBB"
  - "Omicron/BN.1"
  - "Omicron/BA.2.75"
  - "Omicron/BA.4"
  - "Omicron/BA.2"
  - "Omicron/BA.1"
  - "Alpha"
  - "Beta"
  - "Gamma"
  - "Delta"
  - "Epsilon"
  - "Zeta"
  - "Eta"
  - "Theta"
  - "Iota"
  - "Kappa"
  - "Lambda"
  - "Mu"
- name: drms
  display: mAb resist. mutations >0.0001%
  dropdown: false
  checkbox: true
  annotStyle: aminoAcids
  color: '#cc3429'
  drmQuery: |-
    SELECT position, amino_acid FROM resistance_mutations drm
    WHERE
      gene = 'S' AND
      EXISTS (
        SELECT 1 FROM amino_acid_prevalence pcnt
        WHERE
          pcnt.gene = drm.gene AND
          pcnt.position = drm.position AND
          pcnt.amino_acid = drm.amino_acid AND
          pcnt.proportion > 0.000001
      )
    ORDER BY position, amino_acid
