taxonomy: SARS2
gene: SARS2RdRP
refSequence: MFVFLVLLPLVSSQCVNLTTRTQLPPAYTNSFTRGVYYPDKVFRSSVLHSTQDLFLPFFSNVTWFHAIHVSGTNGTKRFDNPVLPFNDGVYFASTEKSNIIRGWIFGTTLDSKTQSLLIVNNATNVVIKVCEFQFCNDPFLGVYYHKNNKSWMESEFRVYSSANNCTFEYVSQPFLMDLEGKQGNFKNLREFVFKNIDGYFKIYSKHTPINLVRDLPQGFSALEPLVDLPIGINITRFQTLLALHRSYLTPGDSSSGWTAGAAAYYVGYLQPRTFLLKYNENGTITDAVDCALDPLSETKCTLKSFTVEKGIYQTSNFRVQPTESIVRFPNITNLCPFGEVFNATRFASVYAWNRKRISNCVADYSVLYNSASFSTFKCYGVSPTKLNDLCFTNVYADSFVIRGDEVRQIAPGQTGKIADYNYKLPDDFTGCVIAWNSNNLDSKVGGNYNYLYRLFRKSNLKPFERDISTEIYQAGSTPCNGVEGFNCYFPLQSYGFQPTNGVGYQPYRVVVLSFELLHAPATVCGPKKSTNLVKNKCVNFNFNGLTGTGVLTESNKKFLPFQQFGRDIADTTDAVRDPQTLEILDITPCSFGGVSVITPGTNTSNQVAVLYQDVNCTEVPVAIHADQLTPTWRVYSTGSNVFQTRAGCLIGAEHVNNSYECDIPIGAGICASYQTQTNSPRRARSVASQSIIAYTMSLGAENSVAYSNNSIAIPTNFTISVTTEILPVSMTKTSVDCTMYICGDSTECSNLLLQYGSFCTQLNRALTGIAVEQDKNTQEVFAQVKQIYKTPPIKDFGGFNFSQILPDPSKPSKRSFIEDLLFNKVTLADAGFIKQYGDCLGDIAARDLICAQKFNGLTVLPPLLTDEMIAQYTSALLAGTITSGWTFGAGAALQIPFAMQMAYRFNGIGVTQNVLYENQKLIANQFNSAIGKIQDSLSSTASALGKLQDVVNQNAQALNTLVKQLSSNFGAISSVLNDILSRLDKVEAEVQIDRLITGRLQSLQTYVTQQLIRAAEIRASANLAATKMSECVLGQSKRVDFCGKGYHLMSFPQSAPHGVVFLHVTYVPAQEKNFTTAPAICHDGKAHFPREGVFVSNGTHWFVTQRNFYEPQIITTDNTFVSGNCDVVIGIVNNTVYDPLQPELDSFKEELDKYFKNHTSPDVDLGDISGINASVVNIQKEIDRLNEVAKNLNESLIDLQELGKYEQYIKWPWYIWLGFIAGLIAIVMVTIMLCCMTSCCSCLKGCCSCGSCCKFDEDDSEPVLKGVKLHYT
fragmentOptions:
- name: S1
  seqFragment: [1, 686]
- name: RBD
  seqFragment: [306, 534]
- name: S2
  seqFragment: [681, 1273]
- name: All
  seqFragment: [1, 1273]
annotCategories:
- name: subdomain
  dropdown: false
  defaultAnnot: subdomain
  multiSelect: false
  annotStyle: colorBox
  annotNames: [subdomain]
- name: ace2
  dropdown: false
  defaultAnnot: ACE2
  multiSelect: false
  annotStyle: circleInBox
  annotNames: [ACE2]
- name: epitopes
  display: mAb epitope
  dropdown: true
  defaultAnnots: []
  multiSelect: true
  annotStyle: underscore
  annotNames:
  - 2-4 epitope
  - 2H2 epitope
  - 3C1 epitope
  - 4A8 epitope
  - B38 epitope
  - BD-23 epitope
  - BD-236 epitope
  - BD-368-2 epitope
  - BD-604 epitope
  - BD-629 epitope
  - C002 epitope
  - C102 epitope
  - C104 epitope
  - C105 epitope
  - C110 epitope
  - C119 epitope
  - C121 epitope
  - C135 epitope
  - C144 epitope
  - C1A-B12 epitope
  - C1A-B3 epitope
  - C1A-C2 epitope
  - C1A-F10 epitope
  - CB6 epitope
  - CC12.1 epitope
  - CC12.3 epitope
  - COVA1-16 epitope
  - COVA2-04 epitope
  - COVA2-39 epitope
  - CR3022 epitope
  - CV30 epitope
  - CV07-250 epitope
  - CV07-270 epitope
  - DH1047 epitope
  - DH1050.1 epitope
  - EY6A epitope
  - Fab-298 epitope
  - Fab-52 epitope
  - FC05 epitope
  - H014 epitope
  - H11-D4 epitope
  - H11-H4 epitope
  - LY-CoV481 epitope
  - LY-CoV488 epitope
  - LY-CoV555 epitope
  - MR17 epitope
  - MR17-K99Y epitope
  - nb20 epitope
  - Nb6 epitope
  - P17 epitope
  - P2B-2F6 epitope
  - P2C-1A3 epitope
  - P2C-1F11 epitope
  - P4A1 epitope
  - S2A4 epitope
  - S2E12 epitope
  - S2H13 epitope
  - S2H14 epitope
  - S2M11 epitope
  - S304 epitope
  - REGN10933 epitope
  - REGN10987 epitope
  - S309 epitope
  - Sb23 epitope
  - SR4 epitope
  - STE90-C11 epitope
  - Ty1 epitope
- name: polymorphism
  dropdown: true
  defaultAnnot: var2000
  multiSelect: false
  annotStyle: aminoAcids
  color: '#999'
  annotNames:
  - var2000
  - var1000
- name: lineages
  display: lineages
  dropdown: true
  defaultAnnots: []
  multiSelect: true
  annotStyle: aminoAcids
  color: '#483d8b'
  annotNames:
  - "lineage B.1.1.7"
  - "lineage 501.V2"
  - "lineage Cluster 5"
- name: resistance
  display: mAb DRMs
  dropdown: true
  defaultAnnots: []
  multiSelect: true
  annotStyle: aminoAcids
  color: '#d23b6f'
  annotNames:
  - resistance 1-20
  - resistance 157
  - resistance 1B07
  - resistance 2-15
  - resistance 2-4
  - resistance 247
  - resistance 261-262
  - resistance 2B04
  - resistance 2H04
  - resistance 4-20
  - resistance AB35
  - resistance B38
  - resistance C121
  - resistance C135
  - resistance C144
  - resistance CA1
  - resistance CB6
  - resistance COV2-2082
  - resistance COV2-2165
  - resistance COV2-2479
  - resistance COV2-2832
  - resistance H00S022
  - resistance H014
  - resistance H4
  - resistance LY-CoV2016
  - resistance P2B-2F6
  - resistance P2C-1F11
  - resistance REGN-COV2
  - resistance REGN10933
  - resistance REGN10934
  - resistance REGN10987
  - resistance REGN10989
  - resistance REGN10989/10934
  - resistance REGN10989/10987
  - resistance S2M11
  - resistance SARS2-01
  - resistance SARS2-02
  - resistance SARS2-07
  - resistance SARS2-16
  - resistance SARS2-19
  - resistance SARS2-21
  - resistance SARS2-22
  - resistance SARS2-23
  - resistance SARS2-31
  - resistance SARS2-32
  - resistance SARS2-34
  - resistance SARS2-55
  - resistance SARS2-58
  - resistance SARS2-66
  - resistance SARS2-71
  - resistance X593
- name: _hide
  display: false
  dropdown: false
  defaultAnnot:
  multiSelect: false
  annotStyle: hide
  annotNames:
  - secondary structure
  - glycan
  - cysteine
  - cleavage
  - subdomain RBM
  - neutralizing sera resistance
conditionalComments:
- commentName: subdomain
  rank: 1  # highest: 1
  requireOtherComment: true  # only include when there's another comment
  condition:
    func: hasAnnotExceptSubgroups
    args: [subdomain, S1/S2, "S2'"]
  prefix:
    func: position
  template: >-
    located in subdomain $SUBDOMAIN
  variables:
    SUBDOMAIN:
      func: getSubgroup
      args: [subdomain]
  triggeredAAs: "*"
- commentName: cleavage
  rank: 2  # highest: 1
  condition:
    func: hasAnnot
    args: [cleavage]
  prefix:
    func: position
  template: >-
    located in cleavage site $CLEAVAGE
  variables:
    CLEAVAGE:
      func: getSubgroup
      args: [cleavage]
  triggeredAAs: "*"
- commentName: ace2
  rank: 3
  condition:
    func: hasAnnot
    args: [ACE2]
  prefix:
    func: position
  template: >-
    involved in ACE2 binding
  footnote: ${FN}
  variables:
    FN:
      func: getCitations
      args: [ACE2]
  triggeredAAs: "*"
- commentName: glycan
  rank: 4
  condition:
    func: hasAnnot
    args: [glycan]
  prefix:
    func: position
  template: >-
    the position of a N-linked glycosylation sequon
  triggeredAAs: "*"
- commentName: epitopes
  rank: 5
  condition:
    func: hasAnnotCategory
    args: [epitopes]
  prefix:
    func: position
  template: >-
    an epitope binding to $ANTIBODIES
  variables:
    ANTIBODIES:
      func: joinSubgroupOfAnnotCat
      args: [epitopes]
      keywords:
        singular_prefix: mAb
        plural_prefix: mAbs
        footnote: true
  triggeredAAs: "*"
- commentName: cysteine
  rank: 6
  condition:
    func: hasAnnot
    args: [cysteine]
  prefix:
    func: position
  template: >-
    one of the nine cysteine residues found in RBD
  triggeredAAs: "*"
- commentName: resistance
  rank: 7
  condition:
    func: hasAnnotCategory
    args: [resistance]
  prefix:
    func: mutationOfAnnotCat
    args: [resistance]
  templateSingular: >-
    a mutation that escape neutralization from $ANTIBODIES
  templatePlural: >-
    mutations that escape neutralization from $ANTIBODIES
  variables:
    ANTIBODIES:
      func: joinAnnotLabelOfAnnotCat
      args: [resistance]
      keywords:
        singular_prefix: mAb
        plural_prefix: mAbs
        footnote: true
  triggeredAAs:
    func: mutationOfAnnotCat
    args: [resistance]
- commentName: polymorphism
  rank: 8
  condition:
    func: hasAnnot
    args: [var2000]
  prefix:
    func: mutation
    args: [var2000]
  templateSingular: >-
    a mutation that is present in published sequences with
    a frequency of $PCNTS$DOT
  templatePlural: >-
    mutations that are present in published sequences with
    a frequency of $PCNTS, respectively$DOT
  triggeredAAs:
    func: mutation
    args: [var2000]
  footnote: ${FN}
  variables:
    PCNTS:
      func: joinAminoAcidAttr
      keywords:
        annot_name: var2000
        attr: prevalence
        format: '{:.2%}'
        last_punc: ''
    FN:
      func: getCitations
      args: [var2000]
    DOT:
      func: getDot
- commentName: lineage
  rank: 9
  condition:
    func: hasAnnotCategory
    args: [lineages]
  prefix:
    func: mutationOfAnnotCat
    args: [lineages]
  templateSingular: >-
    a mutation that observed in $LINEAGES
  templatePlural: >-
    mutations that observed in $LINEAGES
  variables:
    LINEAGES:
      func: joinAnnotLabelOfAnnotCat
      args: [lineages]
      keywords:
        singular_prefix: lineage
        plural_prefix: lineages
        footnote: true
  triggeredAAs:
    func: mutationOfAnnotCat
    args: [lineages]
