#! /usr/bin/env python3
import re
import csv
import json

# This TSV file is generated by
# https://github.com/hivdb/sierra-sars2-paper/blob/main/resistance-mutations.rmd
rows = []

with open('downloads/resistance-mutations/3cl.tsv') as fp:
    for row in csv.DictReader(fp, delimiter='\t'):
        if row['IsDRM'].lower() != 'true':
            continue
        m = re.match(r'^[A-Z](\d+)([A-Z]|ins|del|stop)$', row['Mutation'])
        pos, aa = m.groups()
        rows.append({
            'gene': '_3CLpro',
            'position': int(pos),
            'aa': aa,
            'invivo_selected': row['Mutation'] == 'E166V'
        })

with open('downloads/resistance-mutations/rdrp.tsv') as fp:
    for row in csv.DictReader(fp, delimiter='\t'):
        if row['IsDRM'].lower() != 'true':
            continue
        m = re.match(r'^[A-Z](\d+)([A-Z]|ins|del|stop)$', row['Mutation'])
        pos, aa = m.groups()
        rows.append({
            'gene': 'RdRP',
            'position': int(pos),
            'aa': aa,
            'invivo_selected': row['InVivo'] != ''
        })

with open('downloads/resistance-mutations/latest.tsv') as fp:
    for row in csv.DictReader(fp, delimiter='\t'):
        row['position'] = int(row['position'])
        row['invivo_selected'] = row['invivo_selected'] == 'TRUE'
        rows.append(row)

with open('downloads/resistance-mutations/latest.json', 'w') as fp:
    json.dump({
        'MAB': [row for row in rows if row['gene'] == 'S'],
        '_3CLPI': [row for row in rows if row['gene'] == '_3CLpro'],
        'RdRPI': [row for row in rows if row['gene'] == 'RdRP']
    }, fp, indent=2)

print("Create: downloads/resistance-mutations/latest.json")
